name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: any
  built_collection: '>=2.0.0 <4.0.0'
  built_value: '>=5.5.5 <7.0.0'
  http: ^0.12.0+2
  rxdart: any

  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^0.9.0
  built_value_generator: ^6.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true